【加入】 User tweet 頁面
Lastor-Chen/simple-twitter-express-starter pull request #11
Opened 2019-12-02 18:55 UTC by wendyhsiao

<img src="https://user-images.githubusercontent.com/50958992/69985696-b8dc7000-1576-11ea-8b43-84c94e17094d.png" width="500">

GET /users/:id/tweets 完成相關 route、controller、view，

- route，依照 index 頁面連結而設立了兩個

```
app.get('/users/:id', (req, res) => res.redirect(`/users/${req.user.id}/tweets`))
app.get('/users/:id/tweets', userCtrller.getUser)
```

- User 部分以確認欄位都能正常顯示

  - Username，"/users/:id/tweets"
  - Introduction
  - Tweets，"/users/:id/tweets"
  - Following，"/users/:id/followings"
  - Follower，"/users/:id/followers"
  - Like，"/users/:id/likes"
  - 確認使用者而顯示不同按鈕
  - Edit Profile 按鈕，"/users/:id/edit"
  - Follow 按鈕，form "POST /followships"

- Tweet 部分以確認欄位都能正常顯示
  - Tweet 按照時間新到舊排序
  - 時間格式
  - Username，"/users/:id/tweets"
  - Description
  - Reply，"/tweets/:id/replies"
  - Like，form "POST /tweets/:id/like"

- 其他
  - 使用 Handlebars Helper ，判別頁面為個人或他人的

2019-12-03 14:14 UTC, Lastor-Chen requested changes
* code review 也有提的，比較大的 bug，再稍微抓一下重點
  * 路由 GET "/users/:id" 重新導向，抓的 id 錯誤，會被導向操作者的頁面，而非輸入的 user 頁面
  * controller 丟出來的 user 把登入者的 user 資料覆蓋掉了，需要更名

## 關於 User 多對多 Tweet
這個部分就麻煩 wendy 加一下了，要注意 User 跟 Tweet 有兩層對應關係。
一個是牽扯到 Like 的多對多，
一個是單純的 User 會有多個 Tweet，但 Tweet 只屬於一個 User，也就是 User 一對多 Tweet。
如同妳那邊完成的 ERD 圖，有兩種關係。

這個改完之後，首頁 tweets 應該會爆炸，可以先無視，我再來接著改 XD

2019-12-03 14:14 UTC, Lastor-Chen commented on app.js
> +  helpers: require('./lib/handlebars-helpers')
handlebars 的 helpers 檔名，想商量一下改短成「**hbs_helpers**」，想少打點字......XD
至於是要用串燒還是底線，以前曾經聽說過串燒有些語言、軟體不吃串燒命名，像是 JS 就不吃串燒。
保險起見，檔名用底線會安全點。

2019-12-03 14:14 UTC, Lastor-Chen commented on lib/handlebars-helpers.js
> +    return options.inverse(this)
ifCond，英文直譯是「如果條件」，比較難理解，這邊推薦改成 ifEquels (如果等於)。
至於為啥要加s，我也不知道，我 google 看老外都有加 s，英文文法太難。

另外，這邊有比較精簡的寫法。
(參數盡量避免無語意的 a 跟 b，常規上會用 arg1、arg2，argument 的縮寫，引數的意思)
```
ifEquels: function (arg1, arg2, options) {
    return arg1 === arg2 ? options.fn(this) : options.inverse(this)
}
```

2019-12-03 14:14 UTC, Lastor-Chen commented on routes/index.js
> +  app.get('/users/:id', (req, res) => res.redirect(`/users/${req.user.id}/tweets`))
GET "/users/:id" 
這個地方有些 bug，重新導向抓的 id 應該是頁面的 User id，而不是操作者的 id。
<pre>
app.get('/users/:id', (req, res) => res.redirect(`/users/${<b>req.params.id</b>}/tweets`))
</pre>

2019-12-03 14:14 UTC, Lastor-Chen commented on controllers/userCtrller.js
> +        include: [
這邊 Query User 的寫法是沒有問題的，稍微提供一下簡潔的寫法。
include 裡面有三種寫法。
```
// 完整寫法
include: [{ model: Reply }, {  model: Like }]

// 只寫 model
include: [Reply, Like]

// 寫別名 (當初 model 定義的 as: "別名"，沒有定義 as，預設是 model 名稱 + s)
include: ["Replies", "Likes"]
```

稍微排版一下，佔據的 block 面積可以變小一些。
```
const user = await User.findByPk(req.params.id, {
  include: [
    Like, 'Followers', 'Followings',
    { model: Tweet, include: [Reply, Like] }
  ],
  order: [[Tweet, 'createdAt', 'DESC']]
})
```

2019-12-03 14:14 UTC, Lastor-Chen commented on controllers/userCtrller.js
> +        order: [[{ model: Tweet }, 'createdAt', 'DESC']]
用 "createdAt" 排序時間不是很精確，像是我們目前 seeder 的資料，是幾乎在同時刷出來，
但排序可能會是微妙的..... [9, 8, 6, 5, 7] 之類的，稍微錯亂。

另外，createdAt 雖然是 sequelize-cli 自動生成的命名，
但是小駝峰的命名 postgreSQL 之類比較嚴謹的資料庫，會沒有作用。
所以這類「最新順 or 最舊順」排序，建議直接利用 id 來排序。
```
order: [[Tweet, 'id', 'DESC']]
```

2019-12-03 14:14 UTC, Lastor-Chen commented on controllers/userCtrller.js
> +      return res.render('user', { user, tweets, profileId: req.user.id })
這邊有個比較嚴重，很難發現的邏輯bug。
可以先試著用 root 帳號登入，然後去 GET "/users/1/tweets"。
接著再 GET "/users/2/tweets"。
會發現最上面 navBar 右手邊，Hi user_name 的名稱變了。

因為這邊把 app.js 寫給 handlebars 的 user 變數給覆蓋掉了。
<pre>
// app.js
res.locales.user = req.user

// userCtrller.js
return res.render('user', { <b>user</b>, tweets, profileId: req.user.id })
</pre>

這邊 ctrller 的 user 變數一定要改名，不然操作者的 req.user 整包都會被換成頁面 user。
可以取 `showedUser (被顯示的 User)` 或是 `pageUser (頁面User)` 來做區別。
<pre>
const showedUser = await User.findByPk(...)
</pre>

2019-12-03 14:14 UTC, Lastor-Chen commented on views/user.hbs
> +<div class="row mt-4 no-gutters">
雖然不知道這頁面會不會使用到 alert flash message，
不過為了給它預留空間，這邊 margin-top 還是改成 5 比較好。
<pre>
&lt;div class="row <b>mt-5</b> no-gutters">
</pre>

2019-12-03 14:14 UTC, Lastor-Chen commented on views/user.hbs
> +            <a href="/users/{{user.id}}/tweets">Tweets {{user.Tweets.length}}</a>
因為 controller 已經有丟 tweets 了。可以直接用
<pre>
&lt;a href="/users/{{user.id}}/tweets">Tweets {{<b>tweets.length</b>}}</a>
</pre>

2019-12-03 17:05 UTC, wendyhsiao commented
已修改上述問題，並把 User、Tweet 多對多關係加入 model，

- User 可透過 'LikedTweets' 取得 已按Like 的 tweet
- Tweet 可透過 'LikedUsers' 取得喜歡此 tweet 的使用者

2019-12-04 03:09 UTC, Lastor-Chen approved these changes

2019-12-04 03:27 UTC, Lastor-Chen commented
我這邊直接把一些繁瑣的地方修改掉。

#### [修改] model Like，移除掉多餘設定
Like 裡面不需要加上 id 的 schema，因為 migration 已經設定了。
另外，User 與 Tweet 已經透過 Like 建立多對多，Like 本身不需要在建立一對多關聯。

<br>

#### [修改] hbs helpers 英拼錯字
單純我在 review 的時候打錯字，應該是 `ifEquals` 不是 `ifEquels`。

<br>

#### [優化] getUser 中，isLiked 判斷寫法
`.map()` + `.includes()` 程式會把內容全部遍歷一次，返回一個新陣列再篩選一次，比較吃效能。

改用 `.some()` 方法，簡單優雅。

<br>

#### [debug] 修正所有 user 頁面皆顯示 Edit Profile 按鈕問題
getUser 裡面，將 user 變數更名成 showedUser 之後，似乎忘記修改 hbs 內容。
這邊應該是要比較，`showedUser.id` 是否等於 `req.user.id`。 
<pre>
{{#ifEquals <b>showedUser.id</b> user.id}}
</pre>

另外，最開始 app.js 已經將登入者的 req.user 傳給 handlebars 了，
所以 getUser 不需要再做一個 `profileId` 傳送 `req.user.id`，直接在頁面上使用 `user.id` 即可。
<pre>
// app.js 裡面，儲存到 res.locals 的內容，等同 controller 設定 res.render('page', { <b>變數</b> })
res.locals.user = helpers.getUser(req)

// getUser 的 profileId 可直接移除
res.render('user', { showedUser, tweets, <s>profileId: req.user.id</s> })
</pre>

<br>

### [加入] Like / Unlike 按鈕變換機制
因為我正在做 Like 功能，順手把按鈕先做好。
規格要求 Unlike 是 POST，不是 DELETE，所以不需要加 `?_method=DELETE`

2019-12-04 11:45 UTC, merged