【加入】Profile編輯頁面
Lastor-Chen/simple-twitter-express-starter pull request #13
Opened 2019-12-03 15:39 UTC by TomatoSoup0126

<img width="1440" alt="螢幕快照 2019-12-03 下午11 31 02" src="https://user-images.githubusercontent.com/49901777/70064755-02839400-1625-11ea-9ee7-be14b7d67413.png">

完成下列兩個路由與其MVC
GET  /users/:id/edit 編輯自己的介紹 (表單頁)
POST /users/:id/edit 編輯自己的介紹 (寫入資料庫)

測試請先在本地端根資料夾下新增.env檔案
```
IMGUR_CLIENT_ID='YOUR_CLIENT_ID'
```
手動測試項目：
- GET  /users/:id/edit 應只能GET屬於自己id的編輯頁面，否則會彈回該id的使用者頁面
- POST /users/:id/edit 
   - 需填入名稱才能送出，簡介和頭貼可選擇性修改
   - 新頭貼上傳後應能從imgur重新讀取至原頁面

2019-12-04 06:46 UTC, Lastor-Chen requested changes
## 檢測出一些 bug
* `GET "/users/:id"` 這個路由並不存在，相關的連結 / 重新導向均會出現 `Cannot GET /users/:id` 
  * 手動從網址進入他人的編輯頁面，重新導向錯誤
  * 點擊 update 送出後，重新導向錯誤 (這邊 UX 可能導向到 `/users/:id/tweets` 比較合理 ?)
  * 在 tweets 首頁，點擊右上方的 Profile，無法進入 Profile 頁面

<br>
 
* 目前可以透過 postman 等途徑，修改其他人的 profile，這應該要阻擋下來。
  1. 以 id 2 的 User 登入 
  2. POST "/users/1/edit"
  3. 頁面會導向 "users/1/edit"
  之後會顯示被設定的錯誤訊息 `"別人的資訊只能用看的喔！"`
  但檢查資料庫，會發現資料被成功修改。
  這邊頁面應該要導回 `"users/2/edit"`

<br>

* alert 訊息 UI 錯誤，頁面的最父層要設定 `class="mt-5"`
<img src="https://i.gyazo.com/d639f75df0711ae660d92c0d12482198.png" width="300px">

<br>

* 上傳新圖片之後，仍然會顯示舊圖片，需要 F5 重新整理，才會顯示新圖片。
  * hbs 上抓取的資料，應該 user 都要改成 userResult 即可解決。
  `user.avatar -> userResult.avatar`
<img src="https://i.gyazo.com/1b5dfd7aa29af972544747e3d826c5f9.png" width="300px">


## 需再討論項
* 佈署時 imgur API 要使用誰的?
* 預設 avatar 圖片，要使用 imgur 空間，還是存到專案直接調用?

2019-12-04 14:48 UTC, TomatoSoup0126 commented
<img width="1120" alt="螢幕快照 2019-12-04 下午10 34 43" src="https://user-images.githubusercontent.com/49901777/70152166-afbee080-16e7-11ea-95bb-6d3e1bc638bc.png">

上面幾個問題已修正了
- 替換`/users/:id`成`/users/:id/tweets`
- POST路由先行驗證使用者id與req.params.id是否相符，若不同將導回使用者自己的編輯頁面
- view更新main和edit的排版與變數設定

2019-12-04 17:58 UTC, Lastor-Chen requested changes
有兩個地方還是有點問題：
* tweets 首頁，點右上 Profile 無法進入編輯頁。
* 自己 update 自己的 profile 時，會出現 `只能改自己的資料喔！`訊息，資料有更改成功。
* 強行 update 別人的 profile 時，仍然可以修改資料。

詳細原因，請見下面的 review 細項。

2019-12-04 17:58 UTC, Lastor-Chen commented on controllers/userCtrller.js
> +        res.redirect(`/users/${helpers.getUser(req).id}/edit`)
`req.params.id` 出來的東西是字串，這邊永遠都會不等於而進到 if 中。應該要型轉成 Number。
最後要記得 `return` 不然程式仍然會往下走。
<pre>
if (helpers.getUser(req).id !== <b>+req.params.id</b>) {
  req.flash('error', '只能改自己的資料喔！')
  <b>return</b> res.redirect(`/users/${helpers.getUser(req).id}/edit`)
}
</pre>

2019-12-04 17:58 UTC, Lastor-Chen commented on views/layouts/main.hbs
> +        <a href="/users/{{user.id}}/tweets" class="text-decoration-none text-light mr-2">Profile</a>
Profile 是編輯頁面，連結應該是 edit，不是 tweets。
<pre>
&lt;a href="/users/{{user.id}}/<b>edit</b>" class="text-decoration-none text-light mr-2">Profile</a>
</pre>

2019-12-05 01:09 UTC, TomatoSoup0126 commented on controllers/userCtrller.js
> +        res.redirect(`/users/${helpers.getUser(req).id}/edit`)
沒注意到型別和加上return，感謝提醒，已經修正並推上來了。

2019-12-05 14:25 UTC, Lastor-Chen approved these changes
<img src="https://i.imgur.com/rHarzNb.jpg" width="300px">

2019-12-05 15:40 UTC, merged