Tweet reply page
Lastor-Chen/simple-twitter-express-starter pull request #16
Opened 2019-12-04 18:37 UTC by wendyhsiao

### 完成 GET '/tweets/:tweed_id/replies'

- 前台 User 資料
  - username、Tweets  正確指向 /users/:id/tweets
  - Following  正確指向 /users/:id/followings
  - Follower  正確指向 /users/:id/followers
  - Like  正確指向 /users/:id/likes
  - btn  依照頁面 User 切換 Follow / Edit Profile btn

- 前台 Tweets 資料
  - username  正確指向 /users/:id/tweets
  - Reply  顯示留言則數，正確指向 /tweets/:tweet_id/replies
  - Like  顯示喜歡則數，正確指向 依照登入 User 切換 Like / Unlike btn

- 前台 Replies 資料
  - username  正確指向 /users/:id/tweets
  - 留言順序舊到新 (想說通常最新留言都在最底下)

- 登入不同使用者互相確認

2019-12-05 04:21 UTC, Lastor-Chen requested changes
大致上沒問題，有兩個問題點：
* 發送回文的按鈕文字，應該是 Reply
* <s>tweet.hbs 檔名容易跟 tweets.hbs 混淆，建議改成 userTweet.hbs 或是 user_tweet.hbs</s>

※ 追記：
話說妳這是 replies 頁面，hbs 檔名好像取 replies 辨識度會更高。
現在的 tweet.hbs 改成 userRelies.hbs，比較能配合現在的 RESTful 路由命名。

---------------

另外就是，這條 branch 已經實裝 follow / unfollow 的功能，
記得加到頁面上，follow 功能為了配合 testing，需要藏一個 hidden 的 input 來發送 id。
詳細的做法可以參考 tweets 首頁。

首頁的顯示修復，已在其他 branch 完成，並合併到 master。
這邊可以先臨時性的把 getTweets controller 裡面的這一行改掉，來顯示 tweets 頁面，
方便研究首頁的 follow 功能是如何實作的。
<pre>
tweet.countLikes = tweet.<s>Likes</s>.length
tweet.countLikes = tweet.<b>LikedUsers</b>.length
</pre>

Follow 功能實裝到 reply 頁面之後，記得把 getTweets 的臨時變動改回來，避免跟 master 衝突。

2019-12-05 07:49 UTC, wendyhsiao commented
- 已把 tweet_reply 頁面檔名改為 userReplies.hbs
- 修改推送留言的 Reply 按鈕名稱
- 加入 follow / unfollow 功能

2019-12-05 10:00 UTC, wendyhsiao commented
### **[加入] POST 留言功能**
- 多加了 POST '/tweets/:tweet_id/replies' 

- 確認 Reply 是否符合規定，如不符合會產生警告：

  - 內容不能為空白
  - 內容不可多於 140 字
- 確認使用者可以回覆自己的及其他使用者的推文

2019-12-06 03:49 UTC, Lastor-Chen approved these changes

2019-12-06 03:56 UTC, Lastor-Chen commented
剩下一些零碎小細節，我這邊直接做調整。
* profile 的 follow 按鈕加入 outline 差異，移除置右效果，跟其他頁面統一
* 配合 RESTful 路由命名，將控制器更名
  * `getTweet` to `getReplies`
  * `postTweet` to `postReply`
* postReply 加入成功訊息
* 修正 reply.spec.js 邏輯錯誤，使通過單元測試
* 修正 getReplies 中，無效的 order 寫法，及 time format
* 優化 getReplies 中，database Query 效能

--------------
確認後，可直接合併

2019-12-06 11:26 UTC, merged